### ISSUE TITLE
enable rotation

### ISSUE THREAD

**Issue by a6delali** [AG-iOS/AGVideoPlayerView#1]
Hi

Please how can I force AVPlayerViewController to rotate to landscape when full screen button is clicked

**Comment by AG-iOS** [comment]
@a6delali Hi, I've updated the code, so it's support autorotation now.

**Comment by RamohanReddy** [comment]
Hi @AG-iOS ,
Pls tell me how did you handle landscape mode.

Thanks & Regards
Ramohan Reddy
